package com.gooagoo.api.generator.core.goods;

import java.util.List;

import com.gooagoo.entity.generator.goods.GoodsFeatureInfo;
import com.gooagoo.entity.generator.goods.GoodsFeatureInfoExample;

public interface GoodsFeatureInfoGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询表中对应数据条数
     * @param goodsFeatureInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(GoodsFeatureInfoExample goodsFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param goodsFeatureInfoExample 查询条件
     * @return 
     */
    public List<GoodsFeatureInfo> selectByExample(GoodsFeatureInfoExample goodsFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询数据
     * @param goodsFeatureInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public GoodsFeatureInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public GoodsFeatureInfo selectByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param goodsFeatureInfoExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(GoodsFeatureInfoExample goodsFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于逻辑删除数据（修改is_del值为Y)
     * @param goodsFeatureInfoExample 删除条件
     * @return true-逻辑删除数据成功 false-逻辑删除数据失败
     */
    public boolean deleteByExample(GoodsFeatureInfoExample goodsFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于逻辑删除数据（修改is_del值为Y)
     * @param primaryKey 删除条件 主键
     * @return true-逻辑删除成功 false-逻辑删除失败
     */
    public boolean deleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于往表中添加数据
     * @param goodsFeatureInfo 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(GoodsFeatureInfo goodsFeatureInfo) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param goodsFeatureInfo 更新数据
     * @param goodsFeatureInfoExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(GoodsFeatureInfo goodsFeatureInfo,GoodsFeatureInfoExample goodsFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param goodsFeatureInfo 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(GoodsFeatureInfo goodsFeatureInfo) ;

}
