package com.gooagoo.api.generator.core.base;

import java.util.List;

import com.gooagoo.entity.generator.base.QualitySquareGoodsType;
import com.gooagoo.entity.generator.base.QualitySquareGoodsTypeExample;

public interface QualitySquareGoodsTypeGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于查询表中对应数据条数
     * @param qualitySquareGoodsTypeExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(QualitySquareGoodsTypeExample qualitySquareGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param qualitySquareGoodsTypeExample 查询条件
     * @return 
     */
    public List<QualitySquareGoodsType> selectByExample(QualitySquareGoodsTypeExample qualitySquareGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于查询数据
     * @param qualitySquareGoodsTypeKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public QualitySquareGoodsType selectUnDelByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public QualitySquareGoodsType selectByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param qualitySquareGoodsTypeExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(QualitySquareGoodsTypeExample qualitySquareGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于逻辑删除数据（修改is_del值为Y)
     * @param qualitySquareGoodsTypeExample 删除条件
     * @return true-逻辑删除数据成功 false-逻辑删除数据失败
     */
    public boolean deleteByExample(QualitySquareGoodsTypeExample qualitySquareGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于逻辑删除数据（修改is_del值为Y)
     * @param primaryKey 删除条件 主键
     * @return true-逻辑删除成功 false-逻辑删除失败
     */
    public boolean deleteByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于往表中添加数据
     * @param qualitySquareGoodsType 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(QualitySquareGoodsType qualitySquareGoodsType) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param qualitySquareGoodsType 更新数据
     * @param qualitySquareGoodsTypeExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(QualitySquareGoodsType qualitySquareGoodsType,QualitySquareGoodsTypeExample qualitySquareGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表quality_square_goods_type用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param qualitySquareGoodsType 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(QualitySquareGoodsType qualitySquareGoodsType) ;

}
