package com.gooagoo.api.generator.core.base;

import java.util.List;

import com.gooagoo.entity.generator.base.ShoppingListGoodsType;
import com.gooagoo.entity.generator.base.ShoppingListGoodsTypeExample;

public interface ShoppingListGoodsTypeGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于查询表中对应数据条数
     * @param shoppingListGoodsTypeExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShoppingListGoodsTypeExample shoppingListGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shoppingListGoodsTypeExample 查询条件
     * @return 
     */
    public List<ShoppingListGoodsType> selectByExample(ShoppingListGoodsTypeExample shoppingListGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于查询数据
     * @param shoppingListGoodsTypeKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShoppingListGoodsType selectUnDelByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShoppingListGoodsType selectByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param shoppingListGoodsTypeExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(ShoppingListGoodsTypeExample shoppingListGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于逻辑删除数据（修改is_del值为Y)
     * @param shoppingListGoodsTypeExample 删除条件
     * @return true-逻辑删除数据成功 false-逻辑删除数据失败
     */
    public boolean deleteByExample(ShoppingListGoodsTypeExample shoppingListGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于逻辑删除数据（修改is_del值为Y)
     * @param primaryKey 删除条件 主键
     * @return true-逻辑删除成功 false-逻辑删除失败
     */
    public boolean deleteByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于往表中添加数据
     * @param shoppingListGoodsType 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(ShoppingListGoodsType shoppingListGoodsType) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param shoppingListGoodsType 更新数据
     * @param shoppingListGoodsTypeExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(ShoppingListGoodsType shoppingListGoodsType,ShoppingListGoodsTypeExample shoppingListGoodsTypeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_list_goods_type用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param shoppingListGoodsType 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(ShoppingListGoodsType shoppingListGoodsType) ;

}
