package com.gooagoo.api.generator.core.base;

import java.util.List;

import com.gooagoo.entity.generator.base.SysConfig;
import com.gooagoo.entity.generator.base.SysConfigExample;

public interface SysConfigGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于查询表中对应数据条数
     * @param sysConfigExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(SysConfigExample sysConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param sysConfigExample 查询条件
     * @return 
     */
    public List<SysConfig> selectByExample(SysConfigExample sysConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public SysConfig selectByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param sysConfigExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(SysConfigExample sysConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于往表中添加数据
     * @param sysConfig 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(SysConfig sysConfig) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param sysConfig 更新数据
     * @param sysConfigExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(SysConfig sysConfig,SysConfigExample sysConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param sysConfig 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(SysConfig sysConfig) ;

}
