package com.gooagoo.api.generator.query.member;

import java.util.List;

import com.gooagoo.entity.generator.member.CardUpInfo;
import com.gooagoo.entity.generator.member.CardUpInfoExample;

public interface CardUpInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表card_up_info用于查询表中对应数据条数
     * @param cardUpInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(CardUpInfoExample cardUpInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表card_up_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param cardUpInfoExample 查询条件
     * @return 
     */
    public List<CardUpInfo> selectByExample(CardUpInfoExample cardUpInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表card_up_info用于查询数据
     * @param cardUpInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public CardUpInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表card_up_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public CardUpInfo selectByPrimaryKey(String primaryKey) ;

}
