package com.gooagoo.api.generator.query.member;

import java.util.List;

import com.gooagoo.entity.generator.member.IntegralDetailInfo;
import com.gooagoo.entity.generator.member.IntegralDetailInfoExample;

public interface IntegralDetailInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表integral_detail_info用于查询表中对应数据条数
     * @param integralDetailInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(IntegralDetailInfoExample integralDetailInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表integral_detail_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param integralDetailInfoExample 查询条件
     * @return 
     */
    public List<IntegralDetailInfo> selectByExample(IntegralDetailInfoExample integralDetailInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表integral_detail_info用于查询数据
     * @param integralDetailInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public IntegralDetailInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表integral_detail_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public IntegralDetailInfo selectByPrimaryKey(String primaryKey) ;

}
