package com.gooagoo.api.generator.query.member;

import java.util.List;

import com.gooagoo.entity.generator.member.MemberOfCard;
import com.gooagoo.entity.generator.member.MemberOfCardExample;

public interface MemberOfCardGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_of_card用于查询表中对应数据条数
     * @param memberOfCardExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MemberOfCardExample memberOfCardExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_of_card用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param memberOfCardExample 查询条件
     * @return 
     */
    public List<MemberOfCard> selectByExample(MemberOfCardExample memberOfCardExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_of_card用于查询数据
     * @param memberOfCardKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MemberOfCard selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_of_card用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MemberOfCard selectByPrimaryKey(String primaryKey) ;

}
