package com.gooagoo.api.generator.query.member;

import java.util.List;

import com.gooagoo.entity.generator.member.MemberBaseInfo;
import com.gooagoo.entity.generator.member.MemberBaseInfoExample;

public interface MemberBaseInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_base_info用于查询表中对应数据条数
     * @param memberBaseInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MemberBaseInfoExample memberBaseInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_base_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param memberBaseInfoExample 查询条件
     * @return 
     */
    public List<MemberBaseInfo> selectByExample(MemberBaseInfoExample memberBaseInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_base_info用于查询数据
     * @param memberBaseInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MemberBaseInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_base_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MemberBaseInfo selectByPrimaryKey(String primaryKey) ;

}
