package com.gooagoo.api.generator.query.member;

import java.util.List;

import com.gooagoo.entity.generator.member.MemberFeatureInfo;
import com.gooagoo.entity.generator.member.MemberFeatureInfoExample;

public interface MemberFeatureInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_feature_info用于查询表中对应数据条数
     * @param memberFeatureInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MemberFeatureInfoExample memberFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_feature_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param memberFeatureInfoExample 查询条件
     * @return 
     */
    public List<MemberFeatureInfo> selectByExample(MemberFeatureInfoExample memberFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_feature_info用于查询数据
     * @param memberFeatureInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MemberFeatureInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表member_feature_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MemberFeatureInfo selectByPrimaryKey(String primaryKey) ;

}
