package com.gooagoo.api.generator.query.sys;

import java.util.List;

import com.gooagoo.entity.generator.sys.InterfaceRequestInfo;
import com.gooagoo.entity.generator.sys.InterfaceRequestInfoExample;

public interface InterfaceRequestInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表interface_request_info用于查询表中对应数据条数
     * @param interfaceRequestInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(InterfaceRequestInfoExample interfaceRequestInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表interface_request_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param interfaceRequestInfoExample 查询条件
     * @return 
     */
    public List<InterfaceRequestInfo> selectByExample(InterfaceRequestInfoExample interfaceRequestInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表interface_request_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public InterfaceRequestInfo selectByPrimaryKey(Integer primaryKey) ;

}
