package com.gooagoo.api.generator.query.sys;

import java.util.List;

import com.gooagoo.entity.generator.sys.MobileVersion;
import com.gooagoo.entity.generator.sys.MobileVersionExample;

public interface MobileVersionGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表mobile_version用于查询表中对应数据条数
     * @param mobileVersionExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MobileVersionExample mobileVersionExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表mobile_version用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param mobileVersionExample 查询条件
     * @return 
     */
    public List<MobileVersion> selectByExample(MobileVersionExample mobileVersionExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表mobile_version用于查询数据
     * @param mobileVersionKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MobileVersion selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表mobile_version用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MobileVersion selectByPrimaryKey(String primaryKey) ;

}
