package com.gooagoo.api.generator.query.sys;

import java.util.List;

import com.gooagoo.entity.generator.sys.SysUserRole;
import com.gooagoo.entity.generator.sys.SysUserRoleExample;

public interface SysUserRoleGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_user_role用于查询表中对应数据条数
     * @param sysUserRoleExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(SysUserRoleExample sysUserRoleExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_user_role用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param sysUserRoleExample 查询条件
     * @return 
     */
    public List<SysUserRole> selectByExample(SysUserRoleExample sysUserRoleExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_user_role用于查询数据
     * @param sysUserRoleKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public SysUserRole selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_user_role用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public SysUserRole selectByPrimaryKey(String primaryKey) ;

}
