package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.ConsigneeInfo;
import com.gooagoo.entity.generator.user.ConsigneeInfoExample;

public interface ConsigneeInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表consignee_info用于查询表中对应数据条数
     * @param consigneeInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ConsigneeInfoExample consigneeInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表consignee_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param consigneeInfoExample 查询条件
     * @return 
     */
    public List<ConsigneeInfo> selectByExample(ConsigneeInfoExample consigneeInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表consignee_info用于查询数据
     * @param consigneeInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ConsigneeInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表consignee_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ConsigneeInfo selectByPrimaryKey(String primaryKey) ;

}
