package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.ProductSerialNumber;
import com.gooagoo.entity.generator.user.ProductSerialNumberExample;

public interface ProductSerialNumberGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表product_serial_number用于查询表中对应数据条数
     * @param productSerialNumberExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ProductSerialNumberExample productSerialNumberExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表product_serial_number用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param productSerialNumberExample 查询条件
     * @return 
     */
    public List<ProductSerialNumber> selectByExample(ProductSerialNumberExample productSerialNumberExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表product_serial_number用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ProductSerialNumber selectByPrimaryKey(String primaryKey) ;

}
