package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.ReceiptInfo;
import com.gooagoo.entity.generator.user.ReceiptInfoExample;

public interface ReceiptInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表receipt_info用于查询表中对应数据条数
     * @param receiptInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ReceiptInfoExample receiptInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表receipt_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param receiptInfoExample 查询条件
     * @return 
     */
    public List<ReceiptInfo> selectByExample(ReceiptInfoExample receiptInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表receipt_info用于查询数据
     * @param receiptInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ReceiptInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表receipt_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ReceiptInfo selectByPrimaryKey(String primaryKey) ;

}
