package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.UserEmailactiveCode;
import com.gooagoo.entity.generator.user.UserEmailactiveCodeExample;

public interface UserEmailactiveCodeGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_emailactive_code用于查询表中对应数据条数
     * @param userEmailactiveCodeExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserEmailactiveCodeExample userEmailactiveCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_emailactive_code用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userEmailactiveCodeExample 查询条件
     * @return 
     */
    public List<UserEmailactiveCode> selectByExample(UserEmailactiveCodeExample userEmailactiveCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_emailactive_code用于查询数据
     * @param userEmailactiveCodeKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserEmailactiveCode selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_emailactive_code用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserEmailactiveCode selectByPrimaryKey(String primaryKey) ;

}
