package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.UserSecurityQuestion;
import com.gooagoo.entity.generator.user.UserSecurityQuestionExample;

public interface UserSecurityQuestionGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_question用于查询表中对应数据条数
     * @param userSecurityQuestionExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserSecurityQuestionExample userSecurityQuestionExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_question用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userSecurityQuestionExample 查询条件
     * @return 
     */
    public List<UserSecurityQuestion> selectByExample(UserSecurityQuestionExample userSecurityQuestionExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_question用于查询数据
     * @param userSecurityQuestionKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserSecurityQuestion selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_question用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserSecurityQuestion selectByPrimaryKey(String primaryKey) ;

}
