package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.UserAccountBind;
import com.gooagoo.entity.generator.user.UserAccountBindExample;

public interface UserAccountBindGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_account_bind用于查询表中对应数据条数
     * @param userAccountBindExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserAccountBindExample userAccountBindExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_account_bind用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userAccountBindExample 查询条件
     * @return 
     */
    public List<UserAccountBind> selectByExample(UserAccountBindExample userAccountBindExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_account_bind用于查询数据
     * @param userAccountBindKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserAccountBind selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_account_bind用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserAccountBind selectByPrimaryKey(String primaryKey) ;

}
