package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.UserMobileInfo;
import com.gooagoo.entity.generator.user.UserMobileInfoExample;

public interface UserMobileInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_mobile_info用于查询表中对应数据条数
     * @param userMobileInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserMobileInfoExample userMobileInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_mobile_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userMobileInfoExample 查询条件
     * @return 
     */
    public List<UserMobileInfo> selectByExample(UserMobileInfoExample userMobileInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_mobile_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserMobileInfo selectByPrimaryKey(String primaryKey) ;

}
