package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.UserSecurityCard;
import com.gooagoo.entity.generator.user.UserSecurityCardExample;

public interface UserSecurityCardGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_card用于查询表中对应数据条数
     * @param userSecurityCardExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserSecurityCardExample userSecurityCardExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_card用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userSecurityCardExample 查询条件
     * @return 
     */
    public List<UserSecurityCard> selectByExample(UserSecurityCardExample userSecurityCardExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_card用于查询数据
     * @param userSecurityCardKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserSecurityCard selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_security_card用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserSecurityCard selectByPrimaryKey(String primaryKey) ;

}
