package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.UserMobileCode;
import com.gooagoo.entity.generator.user.UserMobileCodeExample;

public interface UserMobileCodeGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_mobile_code用于查询表中对应数据条数
     * @param userMobileCodeExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserMobileCodeExample userMobileCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_mobile_code用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userMobileCodeExample 查询条件
     * @return 
     */
    public List<UserMobileCode> selectByExample(UserMobileCodeExample userMobileCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_mobile_code用于查询数据
     * @param userMobileCodeKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserMobileCode selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_mobile_code用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserMobileCode selectByPrimaryKey(String primaryKey) ;

}
