package com.gooagoo.api.generator.query.user;

import java.util.List;

import com.gooagoo.entity.generator.user.UserProfile;
import com.gooagoo.entity.generator.user.UserProfileExample;

public interface UserProfileGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_profile用于查询表中对应数据条数
     * @param userProfileExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserProfileExample userProfileExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_profile用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userProfileExample 查询条件
     * @return 
     */
    public List<UserProfile> selectByExample(UserProfileExample userProfileExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_profile用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserProfile selectByPrimaryKey(String primaryKey) ;

}
