package com.gooagoo.api.generator.core.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.BillManual;
import com.gooagoo.entity.generator.bill.BillManualExample;

public interface BillManualGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于查询表中对应数据条数
     * @param billManualExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(BillManualExample billManualExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param billManualExample 查询条件
     * @return 
     */
    public List<BillManual> selectByExample(BillManualExample billManualExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于查询数据
     * @param billManualKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public BillManual selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public BillManual selectByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param billManualExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(BillManualExample billManualExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于逻辑删除数据（修改is_del值为Y)
     * @param billManualExample 删除条件
     * @return true-逻辑删除数据成功 false-逻辑删除数据失败
     */
    public boolean deleteByExample(BillManualExample billManualExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于逻辑删除数据（修改is_del值为Y)
     * @param primaryKey 删除条件 主键
     * @return true-逻辑删除成功 false-逻辑删除失败
     */
    public boolean deleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于往表中添加数据
     * @param billManual 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(BillManual billManual) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param billManual 更新数据
     * @param billManualExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(BillManual billManual,BillManualExample billManualExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_manual用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param billManual 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(BillManual billManual) ;

}
