package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.DeviceWifisensor;
import com.gooagoo.entity.generator.shop.DeviceWifisensorExample;

public interface DeviceWifisensorGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表device_wifisensor用于查询表中对应数据条数
     * @param deviceWifisensorExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(DeviceWifisensorExample deviceWifisensorExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表device_wifisensor用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param deviceWifisensorExample 查询条件
     * @return 
     */
    public List<DeviceWifisensor> selectByExample(DeviceWifisensorExample deviceWifisensorExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表device_wifisensor用于查询数据
     * @param deviceWifisensorKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public DeviceWifisensor selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表device_wifisensor用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public DeviceWifisensor selectByPrimaryKey(String primaryKey) ;

}
