package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.GeneratrixInfo;
import com.gooagoo.entity.generator.shop.GeneratrixInfoExample;

public interface GeneratrixInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表generatrix_info用于查询表中对应数据条数
     * @param generatrixInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(GeneratrixInfoExample generatrixInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表generatrix_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param generatrixInfoExample 查询条件
     * @return 
     */
    public List<GeneratrixInfo> selectByExample(GeneratrixInfoExample generatrixInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表generatrix_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public GeneratrixInfo selectByPrimaryKey(String primaryKey) ;

}
