package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.SectionLineInfo;
import com.gooagoo.entity.generator.shop.SectionLineInfoExample;

public interface SectionLineInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于查询表中对应数据条数
     * @param sectionLineInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(SectionLineInfoExample sectionLineInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param sectionLineInfoExample 查询条件
     * @return 
     */
    public List<SectionLineInfo> selectByExample(SectionLineInfoExample sectionLineInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public SectionLineInfo selectByPrimaryKey(String primaryKey) ;

}
