package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ServiceToolSort;
import com.gooagoo.entity.generator.shop.ServiceToolSortExample;

public interface ServiceToolSortGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表service_tool_sort用于查询表中对应数据条数
     * @param serviceToolSortExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ServiceToolSortExample serviceToolSortExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表service_tool_sort用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param serviceToolSortExample 查询条件
     * @return 
     */
    public List<ServiceToolSort> selectByExample(ServiceToolSortExample serviceToolSortExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表service_tool_sort用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ServiceToolSort selectByPrimaryKey(String primaryKey) ;

}
