package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ShopUserInfo;
import com.gooagoo.entity.generator.shop.ShopUserInfoExample;

public interface ShopUserInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_user_info用于查询表中对应数据条数
     * @param shopUserInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopUserInfoExample shopUserInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_user_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopUserInfoExample 查询条件
     * @return 
     */
    public List<ShopUserInfo> selectByExample(ShopUserInfoExample shopUserInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_user_info用于查询数据
     * @param shopUserInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopUserInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_user_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopUserInfo selectByPrimaryKey(String primaryKey) ;

}
