package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ShopLidDetail;
import com.gooagoo.entity.generator.shop.ShopLidDetailExample;

public interface ShopLidDetailGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_lid_detail用于查询表中对应数据条数
     * @param shopLidDetailExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopLidDetailExample shopLidDetailExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_lid_detail用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopLidDetailExample 查询条件
     * @return 
     */
    public List<ShopLidDetail> selectByExample(ShopLidDetailExample shopLidDetailExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_lid_detail用于查询数据
     * @param shopLidDetailKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopLidDetail selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_lid_detail用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopLidDetail selectByPrimaryKey(String primaryKey) ;

}
