package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ShopRole;
import com.gooagoo.entity.generator.shop.ShopRoleExample;

public interface ShopRoleGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role用于查询表中对应数据条数
     * @param shopRoleExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopRoleExample shopRoleExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopRoleExample 查询条件
     * @return 
     */
    public List<ShopRole> selectByExample(ShopRoleExample shopRoleExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role用于查询数据
     * @param shopRoleKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopRole selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopRole selectByPrimaryKey(String primaryKey) ;

}
