package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ShopInfo;
import com.gooagoo.entity.generator.shop.ShopInfoExample;

public interface ShopInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_info用于查询表中对应数据条数
     * @param shopInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopInfoExample shopInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopInfoExample 查询条件
     * @return 
     */
    public List<ShopInfo> selectByExample(ShopInfoExample shopInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_info用于查询数据
     * @param shopInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopInfo selectByPrimaryKey(String primaryKey) ;

}
