package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ShopRoleAuthority;
import com.gooagoo.entity.generator.shop.ShopRoleAuthorityExample;

public interface ShopRoleAuthorityGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role_authority用于查询表中对应数据条数
     * @param shopRoleAuthorityExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopRoleAuthorityExample shopRoleAuthorityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role_authority用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopRoleAuthorityExample 查询条件
     * @return 
     */
    public List<ShopRoleAuthority> selectByExample(ShopRoleAuthorityExample shopRoleAuthorityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role_authority用于查询数据
     * @param shopRoleAuthorityKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopRoleAuthority selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_role_authority用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopRoleAuthority selectByPrimaryKey(String primaryKey) ;

}
