package com.gooagoo.api.generator.query.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ShopEntityInfo;
import com.gooagoo.entity.generator.shop.ShopEntityInfoExample;

public interface ShopEntityInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_entity_info用于查询表中对应数据条数
     * @param shopEntityInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopEntityInfoExample shopEntityInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_entity_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopEntityInfoExample 查询条件
     * @return 
     */
    public List<ShopEntityInfo> selectByExample(ShopEntityInfoExample shopEntityInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_entity_info用于查询数据
     * @param shopEntityInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopEntityInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_entity_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopEntityInfo selectByPrimaryKey(String primaryKey) ;

}
