package com.gooagoo.api.generator.core.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.SectionLineInfo;
import com.gooagoo.entity.generator.shop.SectionLineInfoExample;

public interface SectionLineInfoGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于查询表中对应数据条数
     * @param sectionLineInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(SectionLineInfoExample sectionLineInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param sectionLineInfoExample 查询条件
     * @return 
     */
    public List<SectionLineInfo> selectByExample(SectionLineInfoExample sectionLineInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public SectionLineInfo selectByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param sectionLineInfoExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(SectionLineInfoExample sectionLineInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于往表中添加数据
     * @param sectionLineInfo 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(SectionLineInfo sectionLineInfo) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param sectionLineInfo 更新数据
     * @param sectionLineInfoExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(SectionLineInfo sectionLineInfo,SectionLineInfoExample sectionLineInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表section_line_info用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param sectionLineInfo 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(SectionLineInfo sectionLineInfo) ;

}
