package com.gooagoo.api.generator.core.shop;

import java.util.List;

import com.gooagoo.entity.generator.shop.ShopAuthority;
import com.gooagoo.entity.generator.shop.ShopAuthorityExample;

public interface ShopAuthorityGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于查询表中对应数据条数
     * @param shopAuthorityExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopAuthorityExample shopAuthorityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopAuthorityExample 查询条件
     * @return 
     */
    public List<ShopAuthority> selectByExample(ShopAuthorityExample shopAuthorityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于查询数据
     * @param shopAuthorityKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopAuthority selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopAuthority selectByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param shopAuthorityExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(ShopAuthorityExample shopAuthorityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于逻辑删除数据（修改is_del值为Y)
     * @param shopAuthorityExample 删除条件
     * @return true-逻辑删除数据成功 false-逻辑删除数据失败
     */
    public boolean deleteByExample(ShopAuthorityExample shopAuthorityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于逻辑删除数据（修改is_del值为Y)
     * @param primaryKey 删除条件 主键
     * @return true-逻辑删除成功 false-逻辑删除失败
     */
    public boolean deleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于往表中添加数据
     * @param shopAuthority 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(ShopAuthority shopAuthority) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param shopAuthority 更新数据
     * @param shopAuthorityExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(ShopAuthority shopAuthority,ShopAuthorityExample shopAuthorityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_authority用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param shopAuthority 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(ShopAuthority shopAuthority) ;

}
