package com.gooagoo.api.generator.query.base;

import java.util.List;

import com.gooagoo.entity.generator.base.EmailConfig;
import com.gooagoo.entity.generator.base.EmailConfigExample;

public interface EmailConfigGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表email_config用于查询表中对应数据条数
     * @param emailConfigExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(EmailConfigExample emailConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表email_config用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param emailConfigExample 查询条件
     * @return 
     */
    public List<EmailConfig> selectByExample(EmailConfigExample emailConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表email_config用于查询数据
     * @param emailConfigKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public EmailConfig selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表email_config用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public EmailConfig selectByPrimaryKey(String primaryKey) ;

}
