package com.gooagoo.api.generator.query.base;

import java.util.List;

import com.gooagoo.entity.generator.base.ShopInterfaceName;
import com.gooagoo.entity.generator.base.ShopInterfaceNameExample;

public interface ShopInterfaceNameGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_interface_name用于查询表中对应数据条数
     * @param shopInterfaceNameExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopInterfaceNameExample shopInterfaceNameExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_interface_name用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopInterfaceNameExample 查询条件
     * @return 
     */
    public List<ShopInterfaceName> selectByExample(ShopInterfaceNameExample shopInterfaceNameExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_interface_name用于查询数据
     * @param shopInterfaceNameKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopInterfaceName selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_interface_name用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopInterfaceName selectByPrimaryKey(String primaryKey) ;

}
