package com.gooagoo.api.generator.query.base;

import java.util.List;

import com.gooagoo.entity.generator.base.SysConfig;
import com.gooagoo.entity.generator.base.SysConfigExample;

public interface SysConfigGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于查询表中对应数据条数
     * @param sysConfigExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(SysConfigExample sysConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param sysConfigExample 查询条件
     * @return 
     */
    public List<SysConfig> selectByExample(SysConfigExample sysConfigExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_config用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public SysConfig selectByPrimaryKey(Integer primaryKey) ;

}
