package com.gooagoo.api.generator.query.base;

import java.util.List;

import com.gooagoo.entity.generator.base.SysDictionary;
import com.gooagoo.entity.generator.base.SysDictionaryExample;

public interface SysDictionaryGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_dictionary用于查询表中对应数据条数
     * @param sysDictionaryExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(SysDictionaryExample sysDictionaryExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_dictionary用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param sysDictionaryExample 查询条件
     * @return 
     */
    public List<SysDictionary> selectByExample(SysDictionaryExample sysDictionaryExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_dictionary用于查询数据
     * @param sysDictionaryKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public SysDictionary selectUnDelByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表sys_dictionary用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public SysDictionary selectByPrimaryKey(Integer primaryKey) ;

}
