package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.CouponGrantInfo;
import com.gooagoo.entity.generator.marketing.CouponGrantInfoExample;

public interface CouponGrantInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表coupon_grant_info用于查询表中对应数据条数
     * @param couponGrantInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(CouponGrantInfoExample couponGrantInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表coupon_grant_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param couponGrantInfoExample 查询条件
     * @return 
     */
    public List<CouponGrantInfo> selectByExample(CouponGrantInfoExample couponGrantInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表coupon_grant_info用于查询数据
     * @param couponGrantInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public CouponGrantInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表coupon_grant_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public CouponGrantInfo selectByPrimaryKey(String primaryKey) ;

}
