package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.MarketingView;
import com.gooagoo.entity.generator.marketing.MarketingViewExample;

public interface MarketingViewGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_view用于查询表中对应数据条数
     * @param marketingViewExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MarketingViewExample marketingViewExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_view用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param marketingViewExample 查询条件
     * @return 
     */
    public List<MarketingView> selectByExample(MarketingViewExample marketingViewExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_view用于查询数据
     * @param marketingViewKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MarketingView selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_view用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MarketingView selectByPrimaryKey(String primaryKey) ;

}
