package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.MarketingItemLink;
import com.gooagoo.entity.generator.marketing.MarketingItemLinkExample;

public interface MarketingItemLinkGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_item_link用于查询表中对应数据条数
     * @param marketingItemLinkExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MarketingItemLinkExample marketingItemLinkExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_item_link用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param marketingItemLinkExample 查询条件
     * @return 
     */
    public List<MarketingItemLink> selectByExample(MarketingItemLinkExample marketingItemLinkExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_item_link用于查询数据
     * @param marketingItemLinkKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MarketingItemLink selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_item_link用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MarketingItemLink selectByPrimaryKey(String primaryKey) ;

}
