package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.MarketingEvent;
import com.gooagoo.entity.generator.marketing.MarketingEventExample;

public interface MarketingEventGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_event用于查询表中对应数据条数
     * @param marketingEventExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MarketingEventExample marketingEventExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_event用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param marketingEventExample 查询条件
     * @return 
     */
    public List<MarketingEvent> selectByExample(MarketingEventExample marketingEventExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_event用于查询数据
     * @param marketingEventKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MarketingEvent selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_event用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MarketingEvent selectByPrimaryKey(String primaryKey) ;

}
