package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.NoticeInfo;
import com.gooagoo.entity.generator.marketing.NoticeInfoExample;

public interface NoticeInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表notice_info用于查询表中对应数据条数
     * @param noticeInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(NoticeInfoExample noticeInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表notice_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param noticeInfoExample 查询条件
     * @return 
     */
    public List<NoticeInfo> selectByExample(NoticeInfoExample noticeInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表notice_info用于查询数据
     * @param noticeInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public NoticeInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表notice_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public NoticeInfo selectByPrimaryKey(String primaryKey) ;

}
