package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.RuleInfo;
import com.gooagoo.entity.generator.marketing.RuleInfoExample;

public interface RuleInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表rule_info用于查询表中对应数据条数
     * @param ruleInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(RuleInfoExample ruleInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表rule_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param ruleInfoExample 查询条件
     * @return 
     */
    public List<RuleInfo> selectByExample(RuleInfoExample ruleInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表rule_info用于查询数据
     * @param ruleInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public RuleInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表rule_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public RuleInfo selectByPrimaryKey(String primaryKey) ;

}
