package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.ShopIntegralConvert;
import com.gooagoo.entity.generator.marketing.ShopIntegralConvertExample;

public interface ShopIntegralConvertGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral_convert用于查询表中对应数据条数
     * @param shopIntegralConvertExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopIntegralConvertExample shopIntegralConvertExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral_convert用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopIntegralConvertExample 查询条件
     * @return 
     */
    public List<ShopIntegralConvert> selectByExample(ShopIntegralConvertExample shopIntegralConvertExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral_convert用于查询数据
     * @param shopIntegralConvertKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopIntegralConvert selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral_convert用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopIntegralConvert selectByPrimaryKey(String primaryKey) ;

}
