package com.gooagoo.api.generator.query.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.ShopIntegral;
import com.gooagoo.entity.generator.marketing.ShopIntegralExample;

public interface ShopIntegralGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral用于查询表中对应数据条数
     * @param shopIntegralExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShopIntegralExample shopIntegralExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shopIntegralExample 查询条件
     * @return 
     */
    public List<ShopIntegral> selectByExample(ShopIntegralExample shopIntegralExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral用于查询数据
     * @param shopIntegralKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShopIntegral selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shop_integral用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShopIntegral selectByPrimaryKey(String primaryKey) ;

}
