package com.gooagoo.api.generator.query.behave;

import java.util.List;

import com.gooagoo.entity.generator.behave.FavoriteInfo;
import com.gooagoo.entity.generator.behave.FavoriteInfoExample;

public interface FavoriteInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表favorite_info用于查询表中对应数据条数
     * @param favoriteInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(FavoriteInfoExample favoriteInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表favorite_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param favoriteInfoExample 查询条件
     * @return 
     */
    public List<FavoriteInfo> selectByExample(FavoriteInfoExample favoriteInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表favorite_info用于查询数据
     * @param favoriteInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public FavoriteInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表favorite_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public FavoriteInfo selectByPrimaryKey(String primaryKey) ;

}
