package com.gooagoo.api.generator.query.behave;

import java.util.List;

import com.gooagoo.entity.generator.behave.ShoppingPlanGoods;
import com.gooagoo.entity.generator.behave.ShoppingPlanGoodsExample;

public interface ShoppingPlanGoodsGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_plan_goods用于查询表中对应数据条数
     * @param shoppingPlanGoodsExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(ShoppingPlanGoodsExample shoppingPlanGoodsExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_plan_goods用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param shoppingPlanGoodsExample 查询条件
     * @return 
     */
    public List<ShoppingPlanGoods> selectByExample(ShoppingPlanGoodsExample shoppingPlanGoodsExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_plan_goods用于查询数据
     * @param shoppingPlanGoodsKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public ShoppingPlanGoods selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表shopping_plan_goods用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public ShoppingPlanGoods selectByPrimaryKey(String primaryKey) ;

}
