package com.gooagoo.api.generator.query.behave;

import java.util.List;

import com.gooagoo.entity.generator.behave.UserStoreQueue;
import com.gooagoo.entity.generator.behave.UserStoreQueueExample;

public interface UserStoreQueueGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_store_queue用于查询表中对应数据条数
     * @param userStoreQueueExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserStoreQueueExample userStoreQueueExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_store_queue用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userStoreQueueExample 查询条件
     * @return 
     */
    public List<UserStoreQueue> selectByExample(UserStoreQueueExample userStoreQueueExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_store_queue用于查询数据
     * @param userStoreQueueKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserStoreQueue selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_store_queue用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserStoreQueue selectByPrimaryKey(String primaryKey) ;

}
