package com.gooagoo.api.generator.query.behave;

import java.util.List;

import com.gooagoo.entity.generator.behave.UserShoppingPlan;
import com.gooagoo.entity.generator.behave.UserShoppingPlanExample;

public interface UserShoppingPlanGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_shopping_plan用于查询表中对应数据条数
     * @param userShoppingPlanExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserShoppingPlanExample userShoppingPlanExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_shopping_plan用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userShoppingPlanExample 查询条件
     * @return 
     */
    public List<UserShoppingPlan> selectByExample(UserShoppingPlanExample userShoppingPlanExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_shopping_plan用于查询数据
     * @param userShoppingPlanKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserShoppingPlan selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_shopping_plan用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserShoppingPlan selectByPrimaryKey(String primaryKey) ;

}
