package com.gooagoo.api.generator.query.behave;

import java.util.List;

import com.gooagoo.entity.generator.behave.UserComment;
import com.gooagoo.entity.generator.behave.UserCommentExample;

public interface UserCommentGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_comment用于查询表中对应数据条数
     * @param userCommentExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserCommentExample userCommentExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_comment用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userCommentExample 查询条件
     * @return 
     */
    public List<UserComment> selectByExample(UserCommentExample userCommentExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_comment用于查询数据
     * @param userCommentKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public UserComment selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_comment用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserComment selectByPrimaryKey(String primaryKey) ;

}
