package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.BillInvoiceLog;
import com.gooagoo.entity.generator.bill.BillInvoiceLogExample;

public interface BillInvoiceLogGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_invoice_log用于查询表中对应数据条数
     * @param billInvoiceLogExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(BillInvoiceLogExample billInvoiceLogExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_invoice_log用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param billInvoiceLogExample 查询条件
     * @return 
     */
    public List<BillInvoiceLog> selectByExample(BillInvoiceLogExample billInvoiceLogExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_invoice_log用于查询数据
     * @param billInvoiceLogKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public BillInvoiceLog selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表bill_invoice_log用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public BillInvoiceLog selectByPrimaryKey(String primaryKey) ;

}
