package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.OrderDetailInfo;
import com.gooagoo.entity.generator.bill.OrderDetailInfoExample;

public interface OrderDetailInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表order_detail_info用于查询表中对应数据条数
     * @param orderDetailInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(OrderDetailInfoExample orderDetailInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表order_detail_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param orderDetailInfoExample 查询条件
     * @return 
     */
    public List<OrderDetailInfo> selectByExample(OrderDetailInfoExample orderDetailInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表order_detail_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public OrderDetailInfo selectByPrimaryKey(String primaryKey) ;

}
