package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.OrderCouponInfo;
import com.gooagoo.entity.generator.bill.OrderCouponInfoExample;

public interface OrderCouponInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表order_coupon_info用于查询表中对应数据条数
     * @param orderCouponInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(OrderCouponInfoExample orderCouponInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表order_coupon_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param orderCouponInfoExample 查询条件
     * @return 
     */
    public List<OrderCouponInfo> selectByExample(OrderCouponInfoExample orderCouponInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表order_coupon_info用于查询数据
     * @param orderCouponInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public OrderCouponInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表order_coupon_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public OrderCouponInfo selectByPrimaryKey(String primaryKey) ;

}
