package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.OriginalBillInfo;
import com.gooagoo.entity.generator.bill.OriginalBillInfoExample;

public interface OriginalBillInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表original_bill_info用于查询表中对应数据条数
     * @param originalBillInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(OriginalBillInfoExample originalBillInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表original_bill_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param originalBillInfoExample 查询条件
     * @return 
     */
    public List<OriginalBillInfo> selectByExample(OriginalBillInfoExample originalBillInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表original_bill_info用于查询数据
     * @param originalBillInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public OriginalBillInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表original_bill_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public OriginalBillInfo selectByPrimaryKey(String primaryKey) ;

}
