package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.OriginalBillDetail;
import com.gooagoo.entity.generator.bill.OriginalBillDetailExample;

public interface OriginalBillDetailGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表original_bill_detail用于查询表中对应数据条数
     * @param originalBillDetailExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(OriginalBillDetailExample originalBillDetailExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表original_bill_detail用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param originalBillDetailExample 查询条件
     * @return 
     */
    public List<OriginalBillDetail> selectByExample(OriginalBillDetailExample originalBillDetailExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表original_bill_detail用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public OriginalBillDetail selectByPrimaryKey(String primaryKey) ;

}
