package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.UserOrderCoupon;
import com.gooagoo.entity.generator.bill.UserOrderCouponExample;

public interface UserOrderCouponGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_coupon用于查询表中对应数据条数
     * @param userOrderCouponExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserOrderCouponExample userOrderCouponExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_coupon用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userOrderCouponExample 查询条件
     * @return 
     */
    public List<UserOrderCoupon> selectByExample(UserOrderCouponExample userOrderCouponExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_coupon用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserOrderCoupon selectByPrimaryKey(String primaryKey) ;

}
