package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.UserOrderInfo;
import com.gooagoo.entity.generator.bill.UserOrderInfoExample;

public interface UserOrderInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_info用于查询表中对应数据条数
     * @param userOrderInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserOrderInfoExample userOrderInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userOrderInfoExample 查询条件
     * @return 
     */
    public List<UserOrderInfo> selectByExample(UserOrderInfoExample userOrderInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserOrderInfo selectByPrimaryKey(String primaryKey) ;

}
