package com.gooagoo.api.generator.query.bill;

import java.util.List;

import com.gooagoo.entity.generator.bill.UserOrderDetail;
import com.gooagoo.entity.generator.bill.UserOrderDetailExample;

public interface UserOrderDetailGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_detail用于查询表中对应数据条数
     * @param userOrderDetailExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(UserOrderDetailExample userOrderDetailExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_detail用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param userOrderDetailExample 查询条件
     * @return 
     */
    public List<UserOrderDetail> selectByExample(UserOrderDetailExample userOrderDetailExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表user_order_detail用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public UserOrderDetail selectByPrimaryKey(String primaryKey) ;

}
