package com.gooagoo.api.generator.core.marketing;

import java.util.List;

import com.gooagoo.entity.generator.marketing.MarketingActivity;
import com.gooagoo.entity.generator.marketing.MarketingActivityExample;

public interface MarketingActivityGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于查询表中对应数据条数
     * @param marketingActivityExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(MarketingActivityExample marketingActivityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param marketingActivityExample 查询条件
     * @return 
     */
    public List<MarketingActivity> selectByExample(MarketingActivityExample marketingActivityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于查询数据
     * @param marketingActivityKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public MarketingActivity selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public MarketingActivity selectByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param marketingActivityExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(MarketingActivityExample marketingActivityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于逻辑删除数据（修改is_del值为Y)
     * @param marketingActivityExample 删除条件
     * @return true-逻辑删除数据成功 false-逻辑删除数据失败
     */
    public boolean deleteByExample(MarketingActivityExample marketingActivityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于逻辑删除数据（修改is_del值为Y)
     * @param primaryKey 删除条件 主键
     * @return true-逻辑删除成功 false-逻辑删除失败
     */
    public boolean deleteByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于往表中添加数据
     * @param marketingActivity 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(MarketingActivity marketingActivity) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param marketingActivity 更新数据
     * @param marketingActivityExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(MarketingActivity marketingActivity,MarketingActivityExample marketingActivityExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表marketing_activity用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param marketingActivity 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(MarketingActivity marketingActivity) ;

}
