package com.gooagoo.api.generator.query.goods;

import java.util.List;

import com.gooagoo.entity.generator.goods.GoodsFeatureInfo;
import com.gooagoo.entity.generator.goods.GoodsFeatureInfoExample;

public interface GoodsFeatureInfoGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询表中对应数据条数
     * @param goodsFeatureInfoExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(GoodsFeatureInfoExample goodsFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param goodsFeatureInfoExample 查询条件
     * @return 
     */
    public List<GoodsFeatureInfo> selectByExample(GoodsFeatureInfoExample goodsFeatureInfoExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询数据
     * @param goodsFeatureInfoKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public GoodsFeatureInfo selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_feature_info用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public GoodsFeatureInfo selectByPrimaryKey(String primaryKey) ;

}
