package com.gooagoo.api.generator.query.goods;

import java.util.List;

import com.gooagoo.entity.generator.goods.GoodsBrand;
import com.gooagoo.entity.generator.goods.GoodsBrandExample;

public interface GoodsBrandGeneratorQueryService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_brand用于查询表中对应数据条数
     * @param goodsBrandExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(GoodsBrandExample goodsBrandExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_brand用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param goodsBrandExample 查询条件
     * @return 
     */
    public List<GoodsBrand> selectByExample(GoodsBrandExample goodsBrandExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_brand用于查询数据
     * @param goodsBrandKey 查询条件，is_del默认为N,如果不想使用此条件请设置为null
     * @return 
     */
    public GoodsBrand selectUnDelByPrimaryKey(String primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表goods_brand用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public GoodsBrand selectByPrimaryKey(String primaryKey) ;

}
