package com.gooagoo.api.generator.core.open;

import java.util.List;

import com.gooagoo.entity.generator.open.OauthCode;
import com.gooagoo.entity.generator.open.OauthCodeExample;

public interface OauthCodeGeneratorCoreService
{

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于查询表中对应数据条数
     * @param oauthCodeExample 查询条件
     * @return 数据条数
     */
    public Integer countByExample(OauthCodeExample oauthCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于查询数据，其中 create_time自动设置为当前数据库时间
     * @param oauthCodeExample 查询条件
     * @return 
     */
    public List<OauthCode> selectByExample(OauthCodeExample oauthCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于查询数据
     * @param primaryKey 查询条件，主键
     * @return 
     */
    public OauthCode selectByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param oauthCodeExample 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByExample(OauthCodeExample oauthCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于删除操作（本系统数据库删除操作非物理删除，请慎用）
     * @param primaryKey 删除条件
     * @return true-物理删除数据成功 false-物理删除数据失败
     */
    public boolean physicalDeleteByPrimaryKey(Integer primaryKey) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于往表中添加数据
     * @param oauthCode 插入数据
     * @return true-添加数据成功 false-添加数据失败
     */
    public boolean insertSelective(OauthCode oauthCode) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param oauthCode 更新数据
     * @param oauthCodeExample 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByExampleSelective(OauthCode oauthCode,OauthCodeExample oauthCodeExample) ;

    /**
     * This method was generated by PengYb
     * 此方法对应数据库表oauth_code用于更新数据，其中 create_time不提供修改功能， c_time_stamp自动设置为当前数据库时间
     * @param oauthCode 更新条件
     * @return true-更新数据成功 false-更新数据失败
     */
    public boolean updateByPrimaryKeySelective(OauthCode oauthCode) ;

}
